#!/usr/bin/env python3
"""Build T6 robustness checklist outcomes table from deposited artifacts."""

from __future__ import annotations

import argparse
import csv
import gzip
import json
import math
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd


CHECK_ORDER = [f"R{i}" for i in range(1, 13)]
KEY_CONFIGS = ["empty", "baseline", "full_action", "full_all"]
N_VALUES = [32, 64, 128, 256]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build T6 robustness checklist outcomes.")
    parser.add_argument("--run_summary", default="paper/figdata/run_summary_table.csv.gz")
    parser.add_argument("--scan", default="paper/figdata/scan_rung_table.csv.gz")
    parser.add_argument("--t2_qa", default="paper/figdata/T2_QA.json")
    parser.add_argument("--f3_qa", default="paper/figdata/F3_QA.json")
    parser.add_argument("--f4_qa", default="paper/figdata/F4_QA.json")
    parser.add_argument("--f6_qa", default="paper/figdata/F6_QA.json")
    parser.add_argument("--f7_qa", default="paper/figdata/F7_QA.json")
    parser.add_argument("--f7_stats", default="paper/figdata/F7_tau_stats.csv.gz")
    parser.add_argument("--f8_qa", default="paper/figdata/F8_QA.json")
    parser.add_argument("--f8_sigma_stats", default="paper/figdata/F8_sigma_ratio_stats.csv.gz")
    parser.add_argument("--f8_rev_stats", default="paper/figdata/F8_REV_stats.csv.gz")
    parser.add_argument("--t3_qa", default="paper/figdata/T3_QA.json")
    parser.add_argument("--t5_qa", default="paper/figdata/T5_QA.json")
    parser.add_argument("--out_tex", default="paper/tables/T6_robustness.tex")
    parser.add_argument("--out_csv", default="paper/figdata/T6_robustness.csv")
    parser.add_argument("--out_csv_gz", default="paper/figdata/T6_robustness.csv.gz")
    parser.add_argument("--qa_out", default="paper/figdata/T6_QA.json")
    parser.add_argument("--exp", default="campaign_v3_union")
    return parser.parse_args()


def read_json_optional(path: str) -> Tuple[Optional[dict], Optional[str]]:
    p = Path(path)
    if not p.exists():
        return None, f"missing artifact: {path}"
    try:
        obj = json.loads(p.read_text(encoding="utf-8"))
        if not isinstance(obj, dict):
            return None, f"invalid json object: {path}"
        return obj, None
    except Exception as exc:
        return None, f"failed to parse {path}: {exc}"


def read_csv_optional(path: str) -> Tuple[Optional[pd.DataFrame], Optional[str]]:
    p = Path(path)
    if not p.exists():
        return None, f"missing artifact: {path}"
    try:
        return pd.read_csv(p), None
    except Exception as exc:
        return None, f"failed to read {path}: {exc}"


def to_bool(v: object) -> bool:
    if isinstance(v, bool):
        return v
    if v is None:
        return False
    if isinstance(v, (int, float)):
        return bool(v)
    return str(v).strip().lower() in {"true", "t", "1", "yes", "y"}


def escape_tex(text: object) -> str:
    if text is None:
        return ""
    s = str(text)
    repl = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
        "<": r"\textless{}",
        ">": r"\textgreater{}",
    }
    return "".join(repl.get(ch, ch) for ch in s)


def write_csv(path: Path, rows: List[dict], columns: List[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=columns)
        w.writeheader()
        for r in rows:
            w.writerow({c: r.get(c, "") for c in columns})


def write_csv_gz(path: Path, rows: List[dict], columns: List[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with gzip.open(path, "wt", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=columns)
        w.writeheader()
        for r in rows:
            w.writerow({c: r.get(c, "") for c in columns})


def write_tex(path: Path, rows: List[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines: List[str] = []
    lines.append("% Auto-generated by paper/scripts/build_T6_robustness.py")
    lines.append(r"\begin{table*}[t]")
    lines.append(r"\small")
    lines.append(r"\centering")
    lines.append(
        r"\caption{Robustness checklist (pre-registered-like; A10). Outcomes are auto-filled from deposited artifacts where computable; pending items are explicitly marked.}"
    )
    lines.append(r"\label{tab:T6_robustness}")
    lines.append(r"\begin{tabular}{l c p{0.33\linewidth} p{0.16\linewidth} p{0.24\linewidth}}")
    lines.append(r"\toprule")
    lines.append(r"Check & Status & Auto-filled summary & Evidence & Notes \\")
    lines.append(r"\midrule")
    for r in rows:
        check = f"{r['check_id']} {r['check_name']}"
        summary = f"[{r['autofilled']}] {r['value_summary']}"
        lines.append(
            f"{escape_tex(check)} & {escape_tex(r['result_status'])} & {escape_tex(summary)} & "
            f"{escape_tex(r['evidence_assets'])} & {escape_tex(r['notes'])} \\\\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table*}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def make_pending(
    cid: str,
    name: str,
    definition: str,
    missing_assets: List[str],
    notes: str,
) -> dict:
    return {
        "check_id": cid,
        "check_name": name,
        "definition": definition,
        "result_status": "PENDING",
        "autofilled": "no",
        "autofilled_fields": "",
        "evidence_assets": ";".join(missing_assets),
        "value_summary": "pending",
        "notes": notes,
    }


def rung_drop_assessment(drop_map: Dict[int, Dict[str, set]]) -> Tuple[str, str]:
    # PASS only if dropped rungs are top rung only; PARTIAL if any mid/low rung dropped.
    any_mid_drop = False
    parts = []
    for n_val in sorted(drop_map.keys()):
        for cfg in sorted(drop_map[n_val].keys()):
            dropped = sorted(drop_map[n_val][cfg])
            if not dropped:
                continue
            top = max(dropped)
            if any(x != top for x in dropped):
                any_mid_drop = True
            parts.append(f"n{n_val}:{cfg}={dropped}")
    if not parts:
        return "PASS", "no support drops recorded"
    if any_mid_drop:
        return "PARTIAL", "; ".join(parts)
    return "PASS", "; ".join(parts)


def main() -> int:
    args = parse_args()

    run_df, run_err = read_csv_optional(args.run_summary)
    scan_df, scan_err = read_csv_optional(args.scan)
    t2_qa, t2_err = read_json_optional(args.t2_qa)
    f3_qa, f3_err = read_json_optional(args.f3_qa)
    f4_qa, f4_err = read_json_optional(args.f4_qa)
    f6_qa, f6_err = read_json_optional(args.f6_qa)
    f7_qa, f7_err = read_json_optional(args.f7_qa)
    f8_qa, f8_err = read_json_optional(args.f8_qa)
    t3_qa, t3_err = read_json_optional(args.t3_qa)
    t5_qa, t5_err = read_json_optional(args.t5_qa)
    f7_stats, f7s_err = read_csv_optional(args.f7_stats)
    f8_sigma_stats, f8s_err = read_csv_optional(args.f8_sigma_stats)
    f8_rev_stats, f8r_err = read_csv_optional(args.f8_rev_stats)

    found_artifacts = {
        "run_summary": run_err is None,
        "scan": scan_err is None,
        "T2_QA": t2_err is None,
        "F3_QA": f3_err is None,
        "F4_QA": f4_err is None,
        "F6_QA": f6_err is None,
        "F7_QA": f7_err is None,
        "F7_tau_stats": f7s_err is None,
        "F8_QA": f8_err is None,
        "F8_sigma_stats": f8s_err is None,
        "F8_REV_stats": f8r_err is None,
        "T3_QA": t3_err is None,
        "T5_QA": t5_err is None,
    }

    missing_artifacts = {
        k: v
        for k, v in {
            "run_summary": run_err,
            "scan": scan_err,
            "T2_QA": t2_err,
            "F3_QA": f3_err,
            "F4_QA": f4_err,
            "F6_QA": f6_err,
            "F7_QA": f7_err,
            "F7_tau_stats": f7s_err,
            "F8_QA": f8_err,
            "F8_sigma_stats": f8s_err,
            "F8_REV_stats": f8r_err,
            "T3_QA": t3_err,
            "T5_QA": t5_err,
        }.items()
        if v is not None
    }

    if run_df is not None:
        run_df["n"] = pd.to_numeric(run_df["n"], errors="coerce").astype("Int64")
        run_df["seed"] = pd.to_numeric(run_df["seed"], errors="coerce").astype("Int64")
        run_df = run_df.dropna(subset=["n", "seed"]).copy()
        run_df["n"] = run_df["n"].astype(int)
        run_df["seed"] = run_df["seed"].astype(int)
        run_df["tau"] = pd.to_numeric(run_df["tau"], errors="coerce")
        run_df["active_tau"] = pd.to_numeric(run_df["active_tau"], errors="coerce")
        run_df["sigma_ratio"] = pd.to_numeric(run_df["sigma_ratio"], errors="coerce")
        run_df["is_REV_bool"] = run_df["is_REV"].map(to_bool)

    if scan_df is not None:
        scan_df["n"] = pd.to_numeric(scan_df["n"], errors="coerce").astype("Int64")
        scan_df["seed"] = pd.to_numeric(scan_df["seed"], errors="coerce").astype("Int64")
        scan_df["k_rung"] = pd.to_numeric(scan_df["k_rung"], errors="coerce").astype("Int64")
        scan_df = scan_df.dropna(subset=["n", "seed", "k_rung"]).copy()
        scan_df["n"] = scan_df["n"].astype(int)
        scan_df["seed"] = scan_df["seed"].astype(int)
        scan_df["k_rung"] = scan_df["k_rung"].astype(int)

    rows: List[dict] = []
    by_status: Dict[str, List[str]] = {"PASS": [], "PARTIAL": [], "FAIL": [], "PENDING": []}

    def push(row: dict) -> None:
        rows.append(row)
        by_status[row["result_status"]].append(row["check_id"])

    # R1 Coverage completeness.
    if run_df is None:
        push(make_pending("R1", "Coverage completeness", "69×3×10 run coverage", ["run_summary_table"], "run summary unavailable"))
    else:
        total = int(len(run_df))
        per_n = {n: int(len(run_df[run_df["n"] == n])) for n in N_VALUES}
        cfg_per_n = {n: int(run_df[run_df["n"] == n]["config_name"].nunique()) for n in N_VALUES}
        expected_per_n = {32: 690, 64: 690, 128: 690, 256: 237}
        expected_cfg_per_n = {32: 69, 64: 69, 128: 69, 256: 26}
        ok = total == 2307 and all(per_n[n] == expected_per_n[n] for n in N_VALUES) and all(
            cfg_per_n[n] == expected_cfg_per_n[n] for n in N_VALUES
        )
        push(
            {
                "check_id": "R1",
                "check_name": "Coverage completeness",
                "definition": "expected vs observed configs×n×seeds coverage",
                "result_status": "PASS" if ok else "FAIL",
                "autofilled": "yes",
                "autofilled_fields": "count;per_n;configs_per_n",
                "evidence_assets": "run_summary_table;T2_QA",
                "value_summary": (
                    f"runs={total}/2307; "
                    f"per_n=32:{per_n[32]},64:{per_n[64]},128:{per_n[128]},256:{per_n[256]}; "
                    f"cfg_per_n=32:{cfg_per_n[32]},64:{cfg_per_n[64]},128:{cfg_per_n[128]},256:{cfg_per_n[256]}"
                ),
                "notes": "Exact coverage required.",
            }
        )

    # R2 Seed support per (config,n).
    if run_df is None:
        push(make_pending("R2", "Seed support per (config,n)", "min/median/max seed support per condition", ["run_summary_table"], "run summary unavailable"))
    else:
        s = run_df.groupby(["config_name", "n"])["seed"].nunique()
        s_min, s_med, s_max = int(s.min()), int(s.median()), int(s.max())
        core = s[s.index.get_level_values("n").isin([32, 64, 128])]
        n256 = s[s.index.get_level_values("n") == 256]
        core_ok = (
            not core.empty
            and int(core.min()) == 10
            and int(core.median()) == 10
            and int(core.max()) == 10
        )
        n256_min = int(n256.min()) if not n256.empty else 0
        if core_ok and n256_min == 10:
            status = "PASS"
        elif core_ok and n256_min >= 5:
            status = "PARTIAL"
        else:
            status = "FAIL"
        push(
            {
                "check_id": "R2",
                "check_name": "Seed support per (config,n)",
                "definition": "min/median/max unique seeds in each config,n cell",
                "result_status": status,
                "autofilled": "yes",
                "autofilled_fields": "seed_min;seed_median;seed_max",
                "evidence_assets": "run_summary_table;T2_QA",
                "value_summary": f"seeds_per_(config,n)={s_min}/{s_med}/{s_max}",
                "notes": "n<=128 expected 10/10/10; n=256 selective suite allows partial seeds.",
            }
        )

    # R3 PICA config consistency.
    if t2_qa is None:
        push(make_pending("R3", "PICA config consistency across runs", "pica_config must be invariant within each config", ["T2_QA"], "missing T2_QA.json"))
    else:
        val = bool(t2_qa.get("pica_config_consistency_all_configs", False))
        push(
            {
                "check_id": "R3",
                "check_name": "PICA config consistency across runs",
                "definition": "all runs of same config share identical pica_config",
                "result_status": "PASS" if val else "FAIL",
                "autofilled": "yes",
                "autofilled_fields": "pica_config_consistency_all_configs",
                "evidence_assets": "T2_QA",
                "value_summary": f"pica_config_consistency_all_configs={val}",
                "notes": "Configuration drift would invalidate condition-level claims.",
            }
        )

    # R4 Scan curve min-support enforcement.
    if f3_qa is None and f4_qa is None:
        push(make_pending("R4", "Scan curve min-support enforcement", "support<5 rung drops reviewed for key curves", ["F3_QA", "F4_QA"], "no F3/F4 QA artifacts"))
    else:
        drop_map: Dict[int, Dict[str, set]] = {}
        if f3_qa is not None:
            for n_key, n_obj in f3_qa.items():
                if not str(n_key).startswith("n") or not isinstance(n_obj, dict):
                    continue
                n_val = int(str(n_key)[1:])
                for panel in ["F3a", "F3b"]:
                    p = n_obj.get(panel, {})
                    if not isinstance(p, dict):
                        continue
                    for cfg in KEY_CONFIGS:
                        cfg_obj = p.get(cfg)
                        if isinstance(cfg_obj, dict):
                            dropped = cfg_obj.get("rungs_dropped_low_support", [])
                            drop_map.setdefault(n_val, {}).setdefault(cfg, set()).update(int(x) for x in dropped)
        if f4_qa is not None:
            for n_key, n_obj in f4_qa.items():
                if not str(n_key).startswith("n") or not isinstance(n_obj, dict):
                    continue
                n_val = int(str(n_key)[1:])
                panels = n_obj.get("panels", {})
                if not isinstance(panels, dict):
                    continue
                for panel_name, panel_obj in panels.items():
                    if not isinstance(panel_obj, dict):
                        continue
                    for cfg in ["baseline", "full_action", "full_all"]:
                        cfg_obj = panel_obj.get(cfg)
                        if isinstance(cfg_obj, dict):
                            dropped = cfg_obj.get("rungs_dropped_support", [])
                            drop_map.setdefault(n_val, {}).setdefault(cfg, set()).update(int(x) for x in dropped)
        status, summary = rung_drop_assessment(drop_map)
        notes = "Only top-rung drops expected under support threshold." if status == "PASS" else "Mid/low rung drops observed; interpret affected curves cautiously."
        push(
            {
                "check_id": "R4",
                "check_name": "Scan min-support enforcement",
                "definition": "rung drops due to support<5 across F3/F4 key curves",
                "result_status": status,
                "autofilled": "yes",
                "autofilled_fields": "rungs_dropped;support_reason",
                "evidence_assets": "F3_QA;F4_QA",
                "value_summary": summary,
                "notes": notes,
            }
        )

    # R5 Lagrange probe missingness at scan level (n=128 F4).
    if f4_qa is None and scan_df is None:
        push(make_pending("R5", "Lagrange-probe missingness (n=128)", "missingness for lagr_geo_r2 and lagr_diff_kl", ["F4_QA", "scan_rung_table"], "need F4 QA or scan table"))
    else:
        geo_rates: List[float] = []
        kl_rates: List[float] = []
        source = ""
        if f4_qa is not None:
            n128 = f4_qa.get("n128", {})
            panels = n128.get("panels", {}) if isinstance(n128, dict) else {}
            for cfg in ["baseline", "full_action", "full_all"]:
                c = panels.get("F4c", {}).get(cfg, {})
                d = panels.get("F4d", {}).get(cfg, {})
                if isinstance(c, dict):
                    v = c.get("overall_missingness_rate")
                    if v is not None and math.isfinite(float(v)):
                        geo_rates.append(float(v))
                if isinstance(d, dict):
                    v = d.get("overall_missingness_rate")
                    if v is not None and math.isfinite(float(v)):
                        kl_rates.append(float(v))
            source = "F4_QA"
        if (not geo_rates or not kl_rates) and scan_df is not None:
            sub = scan_df[
                (scan_df["n"] == 128)
                & (scan_df["k_rung"].isin([2, 4, 8, 16, 32, 64]))
                & (scan_df["config_name"].isin(["baseline", "full_action", "full_all"]))
            ].copy()
            for metric, sink in [("lagr_geo_r2", geo_rates), ("lagr_diff_kl", kl_rates)]:
                x = pd.to_numeric(sub[metric], errors="coerce").to_numpy(dtype=float)
                if x.size > 0:
                    sink.append(float((~np.isfinite(x)).mean()))
            source = "scan_rung_table"
        if not geo_rates or not kl_rates:
            push(make_pending("R5", "Lagrange-probe missingness (n=128)", "missingness for lagr_geo_r2 and lagr_diff_kl", ["F4_QA", "scan_rung_table"], "insufficient missingness fields"))
        else:
            geo_mean = float(np.mean(geo_rates))
            kl_mean = float(np.mean(kl_rates))
            overall = float(np.mean([geo_mean, kl_mean]))
            status = "PASS" if overall < 0.25 else "PARTIAL"
            push(
                {
                    "check_id": "R5",
                    "check_name": "Lagrange-probe missingness (n=128)",
                    "definition": "overall missingness for lagr_geo_r2 and lagr_diff_kl",
                    "result_status": status,
                    "autofilled": "yes",
                    "autofilled_fields": "missingness_geo;missingness_diff_kl;overall",
                    "evidence_assets": source,
                    "value_summary": f"geo={geo_mean:.3f}; diff_kl={kl_mean:.3f}; overall={overall:.3f}",
                    "notes": "PASS threshold: overall missingness < 0.25.",
                }
            )

    # R6 tau policy outcomes.
    if f7_stats is None and run_df is None:
        push(make_pending("R6", "Tau policy outcomes", "tau distribution and active_tau rates by config,n", ["F7_tau_stats", "run_summary_table"], "tau summary artifacts unavailable"))
    else:
        source = ""
        if f7_stats is not None:
            d = f7_stats.copy()
            source = "F7_tau_stats;F7_QA"
        else:
            d = run_df[run_df["config_name"].isin(KEY_CONFIGS)].copy()
            g = (
                d.groupby(["n", "config_name"], as_index=False)
                .agg(
                    tau_median=("tau", "median"),
                    tau_min=("tau", "min"),
                    tau_max=("tau", "max"),
                    active_tau_defined_rate=("active_tau", lambda s: float(pd.to_numeric(s, errors="coerce").notna().mean())),
                )
            )
            d = g
            source = "run_summary_table"
        d["n"] = pd.to_numeric(d["n"], errors="coerce")
        d = d[d["n"].isin(N_VALUES)]
        d = d[d["config_name"].isin(KEY_CONFIGS)]
        d["tau_min"] = pd.to_numeric(d["tau_min"], errors="coerce")
        d["tau_max"] = pd.to_numeric(d["tau_max"], errors="coerce")
        d["tau_median"] = pd.to_numeric(d["tau_median"], errors="coerce")
        if "active_tau_defined_rate" in d.columns:
            d["active_tau_defined_rate"] = pd.to_numeric(d["active_tau_defined_rate"], errors="coerce")
        else:
            d["active_tau_defined_rate"] = np.nan
        finite_rates = d["active_tau_defined_rate"].dropna()
        non_degenerate = bool((d["tau_min"] != d["tau_max"]).any())
        rates_reported = int(len(finite_rates)) == len(d)
        status = "PASS" if (non_degenerate and rates_reported and len(d) > 0) else "PARTIAL"
        by_n = []
        for n_val in N_VALUES:
            sub = d[d["n"] == n_val]
            if sub.empty:
                continue
            lo = float(sub["tau_min"].min())
            hi = float(sub["tau_max"].max())
            by_n.append(f"n{n_val}[{lo:.0f},{hi:.0f}]")
        push(
            {
                "check_id": "R6",
                "check_name": "Tau policy outcomes",
                "definition": "tau range and active_tau_defined_rate across key configs and n",
                "result_status": status,
                "autofilled": "yes",
                "autofilled_fields": "tau_min;tau_median;tau_max;active_tau_defined_rate",
                "evidence_assets": source,
                "value_summary": "tau_ranges=" + ",".join(by_n) + f"; rates_reported={rates_reported}",
                "notes": "Differences across configs are expected; reporting completeness is required.",
            }
        )

    # R7 tau overlap feasibility baseline vs full_action.
    if run_df is None:
        push(make_pending("R7", "Tau overlap feasibility", "overlap of tau support between baseline and full_action", ["run_summary_table"], "run summary unavailable"))
    else:
        parts = []
        statuses = []
        for n_val in N_VALUES:
            b = set(pd.to_numeric(run_df[(run_df["n"] == n_val) & (run_df["config_name"] == "baseline")]["tau"], errors="coerce").dropna().astype(int).tolist())
            f = set(pd.to_numeric(run_df[(run_df["n"] == n_val) & (run_df["config_name"] == "full_action")]["tau"], errors="coerce").dropna().astype(int).tolist())
            inter = b & f
            uni = b | f
            overlap = len(inter)
            jacc = overlap / len(uni) if uni else float("nan")
            parts.append(f"n{n_val}:overlap={overlap},jacc={jacc:.3f}")
            if overlap >= 2:
                statuses.append("PASS")
            elif overlap == 1:
                statuses.append("PARTIAL")
            else:
                statuses.append("FAIL")
        if "FAIL" in statuses:
            status = "FAIL"
        elif "PARTIAL" in statuses:
            status = "PARTIAL"
        else:
            status = "PASS"
        note = "FAIL implies direct tau-controlled comparisons are not feasible without additional matching."
        if status == "PASS":
            note = "Overlap adequate for direct tau-controlled comparisons."
        elif status == "PARTIAL":
            note = "Limited overlap for some n; controlled comparisons may be fragile."
        push(
            {
                "check_id": "R7",
                "check_name": "Tau overlap feasibility",
                "definition": "tau support overlap between baseline and full_action",
                "result_status": status,
                "autofilled": "yes",
                "autofilled_fields": "overlap_count;jaccard",
                "evidence_assets": "run_summary_table",
                "value_summary": "; ".join(parts),
                "notes": note,
            }
        )

    # R8 REV prevalence and handling.
    if run_df is None and f8_rev_stats is None:
        push(make_pending("R8", "REV prevalence and handling", "REV rate per n and explicit handling", ["run_summary_table", "F8_REV_stats"], "no REV evidence artifacts"))
    else:
        source = ""
        if run_df is not None:
            base = run_df
            source = "run_summary_table;F8_REV_stats"
            parts = []
            rates = []
            for n_val in N_VALUES:
                sub = base[base["n"] == n_val]
                if sub.empty:
                    continue
                rc = int(sub["is_REV_bool"].sum())
                rt = int(len(sub))
                rr = rc / rt if rt else float("nan")
                parts.append(f"n{n_val}:{rc}/{rt} ({rr:.4f})")
                rates.append(rr)
        else:
            base = f8_rev_stats.copy()
            source = "F8_REV_stats"
            parts = []
            rates = []
            for n_val in N_VALUES:
                sub = base[base["n"] == n_val]
                if sub.empty:
                    continue
                rc = int(sub["rev_count"].sum())
                rt = int(sub["run_count"].sum())
                rr = rc / rt if rt else float("nan")
                parts.append(f"n{n_val}:{rc}/{rt} ({rr:.4f})")
                rates.append(rr)
        low = all((r <= 0.05 for r in rates if math.isfinite(r)))
        status = "PASS" if low and len(rates) == len(N_VALUES) else "PARTIAL"
        push(
            {
                "check_id": "R8",
                "check_name": "REV prevalence and handling",
                "definition": "REV rates per n and explicit handling in analyses",
                "result_status": status,
                "autofilled": "yes",
                "autofilled_fields": "REV_count;REV_rate",
                "evidence_assets": source,
                "value_summary": "; ".join(parts),
                "notes": "REV is explicitly quantified and excluded where required (e.g., T5).",
            }
        )

    # R9 sigma_ratio missingness.
    if f8_qa is None and f8_sigma_stats is None:
        push(make_pending("R9", "sigma_ratio missingness", "missingness of EP-retention proxy by key config,n", ["F8_QA", "F8_sigma_stats"], "missing sigma_ratio QA/stats artifacts"))
    else:
        source = ""
        miss: Dict[int, Dict[str, float]] = {n: {} for n in N_VALUES}
        if f8_qa is not None and isinstance(f8_qa.get("sigma_ratio_missingness"), dict):
            source = "F8_QA;F8_sigma_stats"
            srm = f8_qa["sigma_ratio_missingness"]
            for n_val in N_VALUES:
                key = str(n_val)
                if key in srm and isinstance(srm[key], dict):
                    for cfg in KEY_CONFIGS:
                        c = srm[key].get(cfg, {})
                        if isinstance(c, dict):
                            v = c.get("missing_rate")
                            if v is not None and math.isfinite(float(v)):
                                miss[n_val][cfg] = float(v)
        if all(len(miss[n]) == 0 for n in N_VALUES) and f8_sigma_stats is not None:
            source = "F8_sigma_stats"
            d = f8_sigma_stats.copy()
            d["n"] = pd.to_numeric(d["n"], errors="coerce").astype("Int64")
            d["missing_rate"] = pd.to_numeric(d["missing_rate"], errors="coerce")
            for n_val in N_VALUES:
                for cfg in KEY_CONFIGS:
                    sub = d[(d["n"] == n_val) & (d["config_name"] == cfg)]
                    if not sub.empty:
                        miss[n_val][cfg] = float(sub.iloc[0]["missing_rate"])
        if all(len(miss[n]) == 0 for n in N_VALUES):
            push(make_pending("R9", "sigma_ratio missingness", "missingness of EP-retention proxy by key config,n", ["F8_QA", "F8_sigma_stats"], "unable to parse missingness fields"))
        else:
            full_action_128 = miss.get(128, {}).get("full_action", float("nan"))
            full_all_128 = miss.get(128, {}).get("full_all", float("nan"))
            status = "PASS" if (
                math.isfinite(full_action_128)
                and math.isfinite(full_all_128)
                and full_action_128 <= 0.2
                and full_all_128 <= 0.2
            ) else "PARTIAL"
            parts = []
            for n_val in N_VALUES:
                for cfg in KEY_CONFIGS:
                    if cfg in miss[n_val]:
                        parts.append(f"n{n_val}:{cfg}={miss[n_val][cfg]:.2f}")
            push(
                {
                    "check_id": "R9",
                    "check_name": "sigma_ratio missingness",
                    "definition": "availability of EP-retention proxy across key configs",
                    "result_status": status,
                    "autofilled": "yes",
                    "autofilled_fields": "missing_rate_per_(config,n)",
                    "evidence_assets": source,
                    "value_summary": "; ".join(parts),
                    "notes": "PASS threshold uses n=128 full_action/full_all missingness <= 0.2.",
                }
            )

    # R10 LOO integrity.
    if f6_qa is None:
        push(make_pending("R10", "LOO integrity", "single-removal validity for loo_* configs", ["F6_QA"], "missing F6_QA.json"))
    else:
        valid = int(f6_qa.get("loo_configs_valid_single_removal", 0))
        total = int(f6_qa.get("loo_configs_total", 0))
        status = "PASS" if total > 0 and valid == total == 22 else ("PARTIAL" if total > 0 else "FAIL")
        push(
            {
                "check_id": "R10",
                "check_name": "LOO integrity",
                "definition": "loo_* configs differ by exactly one removed full_action cell",
                "result_status": status,
                "autofilled": "yes",
                "autofilled_fields": "loo_configs_valid_single_removal;loo_configs_total",
                "evidence_assets": "F6_QA;loo_cell_map",
                "value_summary": f"valid_single_removal={valid}/{total}",
                "notes": "Expected 22/22 for strict LOO interpretation.",
            }
        )

    # R11 Headline metric effective N.
    if t3_qa is None:
        push(make_pending("R11", "Headline metric effective N", "minimum n_eff across headline metrics by key config,n", ["T3_QA"], "missing T3_QA.json"))
    else:
        n_eff = t3_qa.get("n_eff", {})
        mins = {}
        weak = []
        for n_val in N_VALUES:
            n_key = str(n_val)
            mins[n_val] = {}
            for cfg in ["empty", "baseline", "full_action", "full_all", "gen6_core_A12_A25"]:
                cfg_map = n_eff.get(n_key, {}).get(cfg, {})
                vals = [int(v) for v in cfg_map.values()] if isinstance(cfg_map, dict) and cfg_map else []
                if vals:
                    m = min(vals)
                    mins[n_val][cfg] = m
                    if m < 8:
                        weak.append((n_val, cfg, m))
        status = "PASS" if not weak and mins else "PARTIAL"
        parts = [f"n{n}:{cfg}={m}" for (n, cfg, m) in weak] if weak else ["all key config/n >= 8"]
        push(
            {
                "check_id": "R11",
                "check_name": "Headline metric effective N",
                "definition": "minimum n_eff across headline metrics per key config,n",
                "result_status": status,
                "autofilled": "yes",
                "autofilled_fields": "n_eff_min_per_(config,n)",
                "evidence_assets": "T3_QA",
                "value_summary": "; ".join(parts),
                "notes": "PARTIAL indicates reduced effective sample size for some config/n blocks.",
            }
        )

    # R12 Anchor-rung k=4 probe coverage and N.
    if t5_qa is None:
        push(make_pending("R12", "Anchor-rung k=4 probe coverage", "N_pair min/max across 6 Spearman pairs by n", ["T5_QA"], "missing T5_QA.json"))
    else:
        corr = t5_qa.get("correlation", {})
        ranges = {}
        status = "PASS"
        min_threshold = {32: 500, 64: 640, 128: 680, 256: 200}
        for n_val in N_VALUES:
            n_key = str(n_val)
            pair_map = corr.get(n_key, {})
            ns = [int(v.get("N_pair", 0)) for v in pair_map.values() if isinstance(v, dict)]
            if not ns:
                ranges[n_val] = (0, 0)
                status = "PARTIAL"
                continue
            lo, hi = min(ns), max(ns)
            ranges[n_val] = (lo, hi)
            if n_val in min_threshold and lo < min_threshold[n_val]:
                status = "PARTIAL"
        summary = "; ".join([f"n{n}:{ranges[n][0]}-{ranges[n][1]}" for n in N_VALUES if n in ranges])
        push(
            {
                "check_id": "R12",
                "check_name": "Anchor-rung k=4 probe coverage",
                "definition": "N_pair min/max across six Spearman pairs at k=4",
                "result_status": status,
                "autofilled": "yes",
                "autofilled_fields": "N_pair_min;N_pair_max",
                "evidence_assets": "T5_QA",
                "value_summary": summary,
                "notes": "Thresholds: n32>=500, n64>=640, n128>=680, n256>=200 for N_pair_min.",
            }
        )

    # Ensure exactly R1..R12.
    rows = sorted(rows, key=lambda r: CHECK_ORDER.index(r["check_id"]))
    if [r["check_id"] for r in rows] != CHECK_ORDER:
        raise SystemExit(f"Internal error: expected check IDs {CHECK_ORDER}, got {[r['check_id'] for r in rows]}")
    if len(rows) != 12:
        raise SystemExit(f"Internal error: expected 12 rows, got {len(rows)}")

    for r in rows:
        if r["result_status"] not in {"PASS", "PARTIAL", "FAIL", "PENDING"}:
            raise SystemExit(f"Invalid status for {r['check_id']}: {r['result_status']}")
        if r.get("autofilled") not in {"yes", "no"}:
            raise SystemExit(f"Invalid autofilled marker for {r['check_id']}: {r.get('autofilled')}")
        if r.get("autofilled") == "no" and not str(r.get("notes", "")).strip():
            raise SystemExit(f"Pending/manual row {r['check_id']} missing explanatory notes")

    columns = [
        "check_id",
        "check_name",
        "definition",
        "result_status",
        "autofilled",
        "autofilled_fields",
        "evidence_assets",
        "value_summary",
        "notes",
    ]

    out_csv = Path(args.out_csv)
    out_csv_gz = Path(args.out_csv_gz)
    out_tex = Path(args.out_tex)
    qa_out = Path(args.qa_out)
    write_csv(out_csv, rows, columns)
    write_csv_gz(out_csv_gz, rows, columns)
    write_tex(out_tex, rows)

    qa = {
        "exp_id": "campaign_v3_union",
        "found_artifacts": found_artifacts,
        "missing_artifacts": missing_artifacts,
        "status_by_check": {r["check_id"]: r["result_status"] for r in rows},
        "checks_by_status": by_status,
    }
    qa_out.parent.mkdir(parents=True, exist_ok=True)
    qa_out.write_text(json.dumps(qa, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    print(f"wrote={out_tex}")
    print(f"wrote={out_csv}")
    print(f"wrote={out_csv_gz}")
    print(f"wrote={qa_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
